In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 30, 40, 50, 60]) #One dimentional array
print(array)
type(array)

[10 20 30 40 50 60]


numpy.ndarray

In [4]:
arr_2D = np.array([[10,30, 50, 70, 90], [20,40,60,80,100]]) #it is two dimentional array
print(arr_2D)

[[ 10  30  50  70  90]
 [ 20  40  60  80 100]]


In [5]:
print(arr_2D.ndim) #for checking the dimention of array

2


In [6]:
arr_2D[0,3] #accessing the element from array by mentioning row & column index

70

In [8]:
arr_2D[0:1,1:4] #Slicing from array

array([[30, 50, 70]])

In [9]:
arr_2D.shape #to check the shape of array

(2, 5)

In [10]:
arr_2D.reshape(5,2) #converting the shape of an array

array([[ 10,  30],
       [ 50,  70],
       [ 90,  20],
       [ 40,  60],
       [ 80, 100]])

In [11]:
#Syntax for arange method : numpy.arange(start, stop, step, dtype)

arr = np.arange(20, 60, 5)

In [12]:
print(arr)

[20 25 30 35 40 45 50 55]


In [13]:
arr_2D.transpose

<function ndarray.transpose>

In [14]:
arr_2D

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100]])

In [15]:
array2 = np.arange(2,10).reshape(4,2)

In [16]:
print(array2)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array_new = np.random.rand(0,1)

In [19]:
print(array_new)

[]


In [20]:
np.random.rand(2,3) #Generating the random numbers metrix

array([[0.35260815, 0.18559917, 0.26937114],
       [0.57259502, 0.83845777, 0.84637543]])

In [21]:
np.random.rand(4,4)

array([[0.82553962, 0.1988922 , 0.09547033, 0.35235893],
       [0.29532624, 0.25981417, 0.90492533, 0.76953171],
       [0.63436949, 0.44097429, 0.30246658, 0.05628257],
       [0.36385827, 0.42179906, 0.59099799, 0.02813674]])

In [22]:
for i in np.nditer(arr_2D): #printing all elements of arrary by using for loop & np.nditer
    print(i)

10
30
50
70
90
20
40
60
80
100


In [23]:
#np.concatenate
arr1= [1,3,5]
arr2 = [2,4,6]
np.concatenate([arr1, arr2])

array([1, 3, 5, 2, 4, 6])

In [27]:
New_array = np.array([11,20,35,41,52,66,73,87,94])
x= np.where(New_array%2==0)
print(x)
# it is showing index number where modulas is zero

(array([1, 4, 5, 8], dtype=int64),)


In [32]:
from numpy import random
arr = np.array([1,2,3,4,5])
b = random.shuffle(arr)
print(arr)
print(b)
# Array sequence will change after every run

[4 1 2 5 3]
None


In [33]:
# Metrix add, sub, multiply & division ----- can be done easily

In [34]:
# np.min(), np.max(), np.diagonal(), np.rot90() ----- can be done easily

In [35]:
np.trace(arr_2D) # it will provide the sum of all diagonal elements of array or matrix

50

In [36]:
# np.mean(arr_2D), np.median(), np.var(), np.std() ---- can be done easily

In [37]:
# np.add(by passing two matrix here), np.divide(), np.multiply(), np.dot(), np.sqrt()  ---- can be done easily